name: PR Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Check plugins
        run: |
          cd ./scripts
          pip install -r requirements.txt
          python manager.py check
        env:
          github_api_token: ${{ secrets.TOKEN_FOR_GITHUB_API }}
