name: Update Meta

on:
  push:
    branches:
      - next
  schedule:
    # Runs at minute 0 of every hour
    - cron: '0 * * * *'

jobs:
  meta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Pull previous meta
        uses: actions/checkout@v2
        with:
          ref: meta
          path: meta

      - name: Fetch data
        run: |
          rm -rf ./meta/.git
          cd ./scripts
          pip install -r requirements.txt
          python manager.py fetch
        env:
          github_api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy meta
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: meta
          FOLDER: meta
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SQUASH_HISTORY: true
          SKIP_EMPTY_COMMITS: true
